# Generated by Django 4.2.16 on 2024-11-10 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_is_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationSKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=255, unique=True)),
                ('presentation', models.CharField(max_length=255)),
                ('dose', models.PositiveIntegerField()),
                ('unit', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medication SKU',
                'verbose_name_plural': 'Medication SKUs',
                'unique_together': {('medication_name', 'presentation', 'dose', 'unit')},
            },
        ),
    ]
