---
name: Checks

# Trgger
on: [push]

# Jobs to run
jobs:
  test-link:
    name: Test and Lint
    runs-on: ubuntu-24.04
    steps:
    # step 1: login to Docker hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
    # step 2: Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

    # step 3: Set up AWS env variables
      - name: Set up aws env variables
        env: 
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRETS_ACCESS_KEY: ${{ secrets.AWS_SECRETS_ACCESS_KEY }}
        AWS_STORAGE_BUCKET_NAME: ${{ secrets.AWS_STORAGE_BUCKET_NAME }}
        AWS_S3_REGION_NAME: ${{ secrets.AWS_S3_REGION_NAME }}

    # step 4: Run tests
      - name: Test
        run: docker compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
      - name: Lint
        run: docker compose run --rm app sh -c "flake8"
        